name = "SmolyakApprox"
uuid = "6b19cf85-48de-5d9d-bfff-465abea14fab"
authors = ["Richard Dennis <richard.dennis@glasgow.ac.uk>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"

[compat]
julia = "^1.3"
ThreadPools = "^2.0"
