name = "SmolyakApprox"
uuid = "6b19cf85-48de-5d9d-bfff-465abea14fab"
authors = ["Richard Dennis <richard.dennis@glasgow.ac.uk>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ChebyshevApprox = "17a596ad-87cd-578c-9b6d-01108c31dc04"

[compat]
julia = "^1.6"
ChebyshevApprox = "^0.4"
